
import 'package:flutter/material.dart';

final List<List<Color>> _backOpt = [
  [
    Colors.grey[850]!,
    Colors.grey[900]!,
    Colors.black,
  ],
  [
    Colors.grey[900]!,
    Colors.grey[900]!,
    Colors.black,
  ],
  [
    Colors.grey[900]!,
    Colors.black,
  ],
  [
    Colors.grey[900]!,
    Colors.black,
    Colors.black,
  ],
  [
    Colors.black,
    Colors.black,
  ]
];

final List<List<Color>> _cardOpt = [
  [
    Colors.grey[850]!,
    Colors.grey[850]!,
    Colors.grey[900]!,
  ],
  [
    Colors.grey[850]!,
    Colors.grey[900]!,
    Colors.grey[900]!,
  ],
  [
    Colors.grey[850]!,
    Colors.grey[900]!,
    Colors.black,
  ],
  [
    Colors.grey[900]!,
    Colors.grey[900]!,
    Colors.black,
  ],
  [
    Colors.grey[900]!,
    Colors.black,
  ],
  [
    Colors.grey[900]!,
    Colors.black,
    Colors.black,
  ],
  [
    Colors.black,
    Colors.black,
  ]
];

final List<List<Color>> _transOpt = [
  [
    Colors.grey[850]!.withOpacity(0.8),
    Colors.grey[900]!.withOpacity(0.9),
    Colors.black.withOpacity(1),
  ],
  [
    Colors.grey[900]!.withOpacity(0.8),
    Colors.grey[900]!.withOpacity(0.9),
    Colors.black.withOpacity(1),
  ],
  [
    Colors.grey[900]!.withOpacity(0.9),
    Colors.black.withOpacity(1),
  ],
  [
    Colors.grey[900]!.withOpacity(0.9),
    Colors.black.withOpacity(0.9),
    Colors.black.withOpacity(1),
  ],
  [
    Colors.black.withOpacity(0.9),
    Colors.black.withOpacity(1),
  ]
];
